grafana:
  adminPassword: admin
  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: windows-local
        scrape_interval: 15s
        static_configs:
          - targets:
              - "host.docker.internal:9182"

alertmanager:
  alertmanagerSpec:
    replicas: 1
